apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-harness
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-sentinel
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: server
    port: {{ .Values.service.serverport }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.service.sentinelport }}
    protocol: TCP
    targetPort: sentinel
  selector:
    release: redis-ha
    app: redis-sentinel
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-harness-announce-0
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-sentinel
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: {{ .Values.service.serverport }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.service.sentinelport }}
    protocol: TCP
    targetPort: sentinel
  selector:
    release: redis-ha
    app: redis-sentinel
    "statefulset.kubernetes.io/pod-name": redis-sentinel-harness-server-0
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-harness-announce-1
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-sentinel
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: {{ .Values.service.serverport }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.service.sentinelport }}
    protocol: TCP
    targetPort: sentinel
  selector:
    release: redis-ha
    app: redis-sentinel
    "statefulset.kubernetes.io/pod-name": redis-sentinel-harness-server-1
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-harness-announce-2
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis-sentinel
    {{- include "redis.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
  - name: server
    port: {{ .Values.service.serverport }}
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: {{ .Values.service.sentinelport }}
    protocol: TCP
    targetPort: sentinel
  selector:
    release: redis-ha
    app: redis-sentinel
    "statefulset.kubernetes.io/pod-name": redis-sentinel-harness-server-2
---
{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus-redis-exporter
    name: redis-exporter-prometheus-redis-exporter
spec:
  ports:
    - name: redis-exporter
      protocol: TCP
      port: 9121
      targetPort: exporter-port
  selector:
    app: redis-sentinel
    release: redis-ha
  clusterIPs:
  type: ClusterIP
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
{{- end }}