# Source: harness-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harness-default
  namespace: {{ .Release.Namespace }}
  annotations: {}
---
# Source: harness-manager/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harness-manager-role
  namespace: {{ .Release.Namespace }}
  annotations: {}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - list
      - watch
---
# Source: harness-manager/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harness-manager-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: harness-manager-role
subjects:
  - kind: ServiceAccount
    name: harness-default
    namespace: {{ .Release.Namespace }}
